sudo: required
services:
  - docker

before_install:
  - docker build -t h0neyman/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run h0neyman/react-test -e CI=true npm test

after_success:
  - docker build -t h0neyman/multi-client ./client
  - docker build -t h0neyman/multi-nginx ./nginx
  - docker build -t h0neyman/multi-server ./server
  - docker build -t h0neyman/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push h0neyman/multi-client
  - docker push h0neyman/multi-nginx
  - docker push h0neyman/multi-server
  - docker push h0neyman/multi-worker
